# Generated by Django 2.2.28 on 2022-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllApps",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.TextField(default="-", null=True)),
                ("Units_info", models.TextField(default="-", null=True)),
                ("NO_storeys", models.TextField(default="-", null=True)),
                (
                    "app_det_res_units_change_type",
                    models.TextField(default="-", null=True),
                ),
                ("app_det_res_units_tenure", models.TextField(default="-", null=True)),
                ("Status", models.TextField(default="-", null=True)),
                (
                    "app_det_left_total_no_proposed_bedrooms",
                    models.TextField(default="-", null=True),
                ),
                (
                    "NO_proposed_residential_units",
                    models.TextField(default="-", null=True),
                ),
                ("london_living_rent", models.TextField(default="-", null=True)),
                ("london_affordable_rent", models.TextField(default="-", null=True)),
                ("affordable_rent", models.TextField(default="-", null=True)),
                ("affordable_units", models.TextField(default="-", null=True)),
                ("market_for_sale", models.TextField(default="-", null=True)),
                ("sociat_rent_units", models.TextField(default="-", null=True)),
                ("intermediate", models.TextField(default="-", null=True)),
                (
                    "market_rent_charged_london_rents",
                    models.TextField(default="-", null=True),
                ),
                ("market_for_rent", models.TextField(default="-", null=True)),
                ("discount_market_sale", models.TextField(default="-", null=True)),
                (
                    "self_build_and_custom_build",
                    models.TextField(default="-", null=True),
                ),
                ("starter_homes", models.TextField(default="-", null=True)),
                ("discount_market_rent", models.TextField(default="-", null=True)),
                (
                    "Existing_residential_affordable_units",
                    models.TextField(default="-", null=True),
                ),
                ("habitable_rooms_density", models.TextField(default="-", null=True)),
                (
                    "Existing_residential_affordable_rent",
                    models.TextField(default="-", null=True),
                ),
                (
                    "Existing_residential_London_shared_ownership",
                    models.TextField(default="-", null=True),
                ),
                (
                    "Existing_residential_London_affordable_rent",
                    models.TextField(default="-", null=True),
                ),
                ("Dwelling_density", models.TextField(default="-", null=True)),
                ("Site_Ares", models.TextField(default="-", null=True)),
                ("Affordable_Percentage", models.TextField(default="-", null=True)),
                (
                    "Existing_residential_units",
                    models.TextField(default="-", null=True),
                ),
                ("centroid", models.TextField(default="-", null=True)),
                ("polygon", models.TextField(default="-", null=True)),
                ("ward", models.TextField(default="-", null=True)),
                ("decision_agency", models.TextField(default="-", null=True)),
                ("site_name", models.TextField(default="-", null=True)),
                ("lpa_app_no", models.TextField(default="-", null=True)),
                ("decision_date", models.TextField(default="-", null=True)),
                ("PostCode", models.TextField(default="-", null=True)),
                ("Unit_type_Studio_Bedsit", models.TextField(default="-", null=True)),
                (
                    "Unit_type_Flat_Apartment_Maisonette",
                    models.TextField(default="-", null=True),
                ),
                ("Provider_Local_Authority", models.TextField(default="-", null=True)),
                (
                    "Provider_Private_rented_sector",
                    models.TextField(default="-", null=True),
                ),
                ("Provider_Private", models.TextField(default="-", null=True)),
                (
                    "Provider_Housing_Association",
                    models.TextField(default="-", null=True),
                ),
                (
                    "Development_type_New_Build",
                    models.TextField(default="-", null=True),
                ),
                (
                    "Development_type_Change_of_Use",
                    models.TextField(default="-", null=True),
                ),
                ("Borough", models.TextField(default="-", null=True)),
                ("App_ID", models.TextField(default="-", null=True)),
                ("Polygon_coords", models.TextField(default="-", null=True)),
                ("latitude", models.TextField(default="-", null=True)),
                ("longitude", models.TextField(default="-", null=True)),
                ("color", models.TextField(default="-", null=True)),
                (
                    "floorspace_detail_actual_completion_date",
                    models.TextField(default="-", null=True),
                ),
                (
                    "floorspace_detail_gia_existing",
                    models.TextField(default="-", null=True),
                ),
                (
                    "floorspace_detail_gia_gained",
                    models.TextField(default="-", null=True),
                ),
                (
                    "floorspace_detail_gia_lost",
                    models.TextField(default="-", null=True),
                ),
                (
                    "floorspace_detail_superseded_by_lpa_app_no",
                    models.TextField(default="-", null=True),
                ),
                (
                    "floorspace_detail_superseded_date",
                    models.TextField(default="-", null=True),
                ),
                (
                    "floorspace_detail_use_class",
                    models.TextField(default="-", null=True),
                ),
                ("Site_area", models.TextField(default="-", null=True)),
                ("parking_net_bluebadge", models.TextField(default="-", null=True)),
                ("parking_net_bus", models.TextField(default="-", null=True)),
                ("parking_net_carclub", models.TextField(default="-", null=True)),
                ("parking_net_cycle", models.TextField(default="-", null=True)),
                ("parking_net_lgv", models.TextField(default="-", null=True)),
                ("parking_net_car", models.TextField(default="-", null=True)),
                ("parking_net_motorcycle", models.TextField(default="-", null=True)),
                ("parking_net_other", models.TextField(default="-", null=True)),
                (
                    "parking_net_resi_offstreet",
                    models.TextField(default="-", null=True),
                ),
                (
                    "parking_no_existing_bluebadge",
                    models.TextField(default="-", null=True),
                ),
                ("parking_no_existing_bus", models.TextField(default="-", null=True)),
                ("parking_no_existing_car", models.TextField(default="-", null=True)),
                (
                    "parking_no_existing_carclub",
                    models.TextField(default="-", null=True),
                ),
                ("parking_no_existing_cycle", models.TextField(default="-", null=True)),
                ("parking_no_existing_lgv", models.TextField(default="-", null=True)),
                (
                    "parking_no_existing_motorcycle",
                    models.TextField(default="-", null=True),
                ),
                ("parking_no_existing_other", models.TextField(default="-", null=True)),
                (
                    "parking_no_existing_resi_offstreet",
                    models.TextField(default="-", null=True),
                ),
                (
                    "parking_no_proposed_bluebadge",
                    models.TextField(default="-", null=True),
                ),
                ("parking_no_proposed_bus", models.TextField(default="-", null=True)),
                ("parking_no_proposed_car", models.TextField(default="-", null=True)),
                (
                    "parking_no_proposed_carclub",
                    models.TextField(default="-", null=True),
                ),
                ("parking_no_proposed_cycle", models.TextField(default="-", null=True)),
                ("parking_no_proposed_lgv", models.TextField(default="-", null=True)),
                (
                    "parking_no_proposed_motorcycle",
                    models.TextField(default="-", null=True),
                ),
                ("parking_no_proposed_other", models.TextField(default="-", null=True)),
                (
                    "parking_no_proposed_resi_offstreet",
                    models.TextField(default="-", null=True),
                ),
            ],
        ),
    ]
