# from . import models
from ..models import TenureData
import pandas as pd


def save_to_database(model, df_tenure_data):
    for i in range(len(df_tenure_data)):
        try:
            b = model(
                source=df_tenure_data["source"][i],
                Units_info=df_tenure_data["Units_info"][i],
                NO_storeys=df_tenure_data["NO_storeys"][i],
                app_det_res_units_change_type=df_tenure_data[
                    "app_det_res_units_change_type"
                ][i],
                app_det_res_units_tenure=df_tenure_data["app_det_res_units_tenure"][i],
                Status=df_tenure_data["Status"][i],
                app_det_left_total_no_proposed_bedrooms=df_tenure_data[
                    "app_det_left_total_no_proposed_bedrooms"
                ][i],
                NO_proposed_residential_units=df_tenure_data[
                    "NO_proposed_residential_units"
                ][i],
                london_living_rent=df_tenure_data["london_living_rent"][i],
                london_affordable_rent=df_tenure_data["london_affordable_rent"][i],
                affordable_rent=df_tenure_data["affordable_rent"][i],
                affordable_units=df_tenure_data["affordable_units"][i],
                market_for_sale=df_tenure_data["market_for_sale"][i],
                sociat_rent_units=df_tenure_data["sociat_rent_units"][i],
                intermediate=df_tenure_data["intermediate"][i],
                market_rent_charged_london_rents=df_tenure_data[
                    "market_rent_charged_london_rents"
                ][i],
                market_for_rent=df_tenure_data["market_for_rent"][i],
                discount_market_sale=df_tenure_data["discount_market_sale"][i],
                self_build_and_custom_build=df_tenure_data[
                    "self_build_and_custom_build"
                ][i],
                starter_homes=df_tenure_data["starter_homes"][i],
                discount_market_rent=df_tenure_data["discount_market_rent"][i],
                Existing_residential_affordable_units=df_tenure_data[
                    "Existing_residential_affordable_units"
                ][i],
                habitable_rooms_density=df_tenure_data["habitable_rooms_density"][i],
                Existing_residential_affordable_rent=df_tenure_data[
                    "Existing_residential_affordable_rent"
                ][i],
                Existing_residential_London_shared_ownership=df_tenure_data[
                    "Existing_residential_London_shared_ownership"
                ][i],
                Existing_residential_London_affordable_rent=df_tenure_data[
                    "Existing_residential_London_affordable_rent"
                ][i],
                Dwelling_density=df_tenure_data["Dwelling_density"][i],
                Site_Ares=df_tenure_data["Site_Ares"][i],
                Affordable_Percentage=df_tenure_data["Affordable_Percentage"][i],
                Existing_residential_units=df_tenure_data["Existing_residential_units"][
                    i
                ],
                centroid=df_tenure_data["centroid"][i],
                polygon=df_tenure_data["polygon"][i],
                ward=df_tenure_data["ward"][i],
                decision_agency=df_tenure_data["decision_agency"][i],
                site_name=df_tenure_data["site_name"][i],
                lpa_app_no=df_tenure_data["lpa_app_no"][i],
                decision_date=str(df_tenure_data["decision_date"][i]).split()[0],
                PostCode=df_tenure_data["PostCode"][i],
                Unit_type_Studio_Bedsit=df_tenure_data["Unit_type_Studio_Bedsit"][i],
                Unit_type_Flat_Apartment_Maisonette=df_tenure_data[
                    "Unit_type_Flat_Apartment_Maisonette"
                ][i],
                Provider_Local_Authority=df_tenure_data["Provider_Local_Authority"][i],
                Provider_Private_rented_sector=df_tenure_data[
                    "Provider_Private_rented_sector"
                ][i],
                Provider_Private=df_tenure_data["Provider_Private"][i],
                Provider_Housing_Association=df_tenure_data[
                    "Provider_Housing_Association"
                ][i],
                Development_type_New_Build=df_tenure_data["Development_type_New_Build"][
                    i
                ],
                Development_type_Change_of_Use=df_tenure_data[
                    "Development_type_Change_of_Use"
                ][i],
                Borough=df_tenure_data["Borough"][i],
                App_ID=df_tenure_data["App_ID"][i],
                Polygon_coords=df_tenure_data["Polygon_coords"][i],
                latitude=df_tenure_data["latitude"][i],
                longitude=df_tenure_data["longitude"][i],
                color=df_tenure_data["color"][i],
                floorspace_detail_actual_completion_date=df_tenure_data[
                    "floorspace_detail_actual_completion_date"
                ][i],
                floorspace_detail_gia_existing=df_tenure_data[
                    "floorspace_detail_gia_existing"
                ][i],
                floorspace_detail_gia_gained=df_tenure_data[
                    "floorspace_detail_gia_gained"
                ][i],
                floorspace_detail_gia_lost=df_tenure_data["floorspace_detail_gia_lost"][
                    i
                ],
                floorspace_detail_superseded_by_lpa_app_no=df_tenure_data[
                    "floorspace_detail_superseded_by_lpa_app_no"
                ][i],
                floorspace_detail_superseded_date=df_tenure_data[
                    "floorspace_detail_superseded_date"
                ][i],
                floorspace_detail_use_class=df_tenure_data[
                    "floorspace_detail_use_class"
                ][i],
                Site_area=df_tenure_data["Site_area"][i],
                parking_net_bluebadge=df_tenure_data["parking_net_bluebadge"][i],
                parking_net_bus=df_tenure_data["parking_net_bus"][i],
                parking_net_carclub=df_tenure_data["parking_net_carclub"][i],
                parking_net_cycle=df_tenure_data["parking_net_cycle"][i],
                parking_net_lgv=df_tenure_data["parking_net_lgv"][i],
                parking_net_car=df_tenure_data["parking_net_car"][i],
                parking_net_motorcycle=df_tenure_data["parking_net_motorcycle"][i],
                parking_net_other=df_tenure_data["parking_net_other"][i],
                parking_net_resi_offstreet=df_tenure_data["parking_net_resi_offstreet"][
                    i
                ],
                parking_no_existing_bluebadge=df_tenure_data[
                    "parking_no_existing_bluebadge"
                ][i],
                parking_no_existing_bus=df_tenure_data["parking_no_existing_bus"][i],
                parking_no_existing_car=df_tenure_data["parking_no_existing_car"][i],
                parking_no_existing_carclub=df_tenure_data[
                    "parking_no_existing_carclub"
                ][i],
                parking_no_existing_cycle=df_tenure_data["parking_no_existing_cycle"][
                    i
                ],
                parking_no_existing_lgv=df_tenure_data["parking_no_existing_lgv"][i],
                parking_no_existing_motorcycle=df_tenure_data[
                    "parking_no_existing_motorcycle"
                ][i],
                parking_no_existing_other=df_tenure_data["parking_no_existing_other"][
                    i
                ],
                parking_no_existing_resi_offstreet=df_tenure_data[
                    "parking_no_existing_resi_offstreet"
                ][i],
                parking_no_proposed_bluebadge=df_tenure_data[
                    "parking_no_proposed_bluebadge"
                ][i],
                parking_no_proposed_bus=df_tenure_data["parking_no_proposed_bus"][i],
                parking_no_proposed_car=df_tenure_data["parking_no_proposed_car"][i],
                parking_no_proposed_carclub=df_tenure_data[
                    "parking_no_proposed_carclub"
                ][i],
                parking_no_proposed_cycle=df_tenure_data["parking_no_proposed_cycle"][
                    i
                ],
                parking_no_proposed_lgv=df_tenure_data["parking_no_proposed_lgv"][i],
                parking_no_proposed_motorcycle=df_tenure_data[
                    "parking_no_proposed_motorcycle"
                ][i],
                parking_no_proposed_other=df_tenure_data["parking_no_proposed_other"][
                    i
                ],
                parking_no_proposed_resi_offstreet=df_tenure_data[
                    "parking_no_proposed_resi_offstreet"
                ][i],
            )
            b.save()

        except KeyError as err:
            print("{} model save to database exception raised: {}.".format(model, err))
            b = model(
                source=df_tenure_data["source"][i],
                Units_info=df_tenure_data["Units_info"][i],
                NO_storeys=df_tenure_data["NO_storeys"][i],
                app_det_res_units_change_type=df_tenure_data[
                    "app_det_res_units_change_type"
                ][i],
                app_det_res_units_tenure=df_tenure_data["app_det_res_units_tenure"][i],
                Status=df_tenure_data["Status"][i],
                app_det_left_total_no_proposed_bedrooms=df_tenure_data[
                    "app_det_left_total_no_proposed_bedrooms"
                ][i],
                NO_proposed_residential_units=df_tenure_data[
                    "NO_proposed_residential_units"
                ][i],
                london_living_rent=df_tenure_data["london_living_rent"][i],
                london_affordable_rent=df_tenure_data["london_affordable_rent"][i],
                affordable_rent=df_tenure_data["affordable_rent"][i],
                affordable_units=df_tenure_data["affordable_units"][i],
                market_for_sale=df_tenure_data["market_for_sale"][i],
                sociat_rent_units=df_tenure_data["sociat_rent_units"][i],
                intermediate=df_tenure_data["intermediate"][i],
                market_rent_charged_london_rents=df_tenure_data[
                    "market_rent_charged_london_rents"
                ][i],
                market_for_rent=df_tenure_data["market_for_rent"][i],
                discount_market_sale=df_tenure_data["discount_market_sale"][i],
                self_build_and_custom_build=df_tenure_data[
                    "self_build_and_custom_build"
                ][i],
                starter_homes=df_tenure_data["starter_homes"][i],
                discount_market_rent=df_tenure_data["discount_market_rent"][i],
                Existing_residential_affordable_units=df_tenure_data[
                    "Existing_residential_affordable_units"
                ][i],
                habitable_rooms_density=df_tenure_data["habitable_rooms_density"][i],
                Existing_residential_affordable_rent=df_tenure_data[
                    "Existing_residential_affordable_rent"
                ][i],
                Existing_residential_London_shared_ownership=df_tenure_data[
                    "Existing_residential_London_shared_ownership"
                ][i],
                Existing_residential_London_affordable_rent=df_tenure_data[
                    "Existing_residential_London_affordable_rent"
                ][i],
                Dwelling_density=df_tenure_data["Dwelling_density"][i],
                Site_Ares=df_tenure_data["Site_Ares"][i],
                Affordable_Percentage=df_tenure_data["Affordable_Percentage"][i],
                Existing_residential_units=df_tenure_data["Existing_residential_units"][
                    i
                ],
                centroid=df_tenure_data["centroid"][i],
                polygon=df_tenure_data["polygon"][i],
                ward=df_tenure_data["ward"][i],
                decision_agency=df_tenure_data["decision_agency"][i],
                site_name=df_tenure_data["site_name"][i],
                lpa_app_no=df_tenure_data["lpa_app_no"][i],
                decision_date=str(df_tenure_data["decision_date"][i]).split()[0],
                PostCode=df_tenure_data["PostCode"][i],
                Unit_type_Studio_Bedsit=df_tenure_data["Unit_type_Studio_Bedsit"][i],
                Unit_type_Flat_Apartment_Maisonette=df_tenure_data[
                    "Unit_type_Flat_Apartment_Maisonette"
                ][i],
                Provider_Local_Authority=None,
                Provider_Private_rented_sector=None,
                Provider_Private=None,
                Provider_Housing_Association=df_tenure_data[
                    "Provider_Housing_Association"
                ][i],
                Development_type_New_Build=df_tenure_data["Development_type_New_Build"][
                    i
                ],
                Development_type_Change_of_Use=df_tenure_data[
                    "Development_type_Change_of_Use"
                ][i],
                Borough=df_tenure_data["Borough"][i],
                App_ID=df_tenure_data["App_ID"][i],
                Polygon_coords=df_tenure_data["Polygon_coords"][i],
                latitude=df_tenure_data["latitude"][i],
                longitude=df_tenure_data["longitude"][i],
                color=df_tenure_data["color"][i],
                floorspace_detail_actual_completion_date=df_tenure_data[
                    "floorspace_detail_actual_completion_date"
                ][i],
                floorspace_detail_gia_existing=df_tenure_data[
                    "floorspace_detail_gia_existing"
                ][i],
                floorspace_detail_gia_gained=df_tenure_data[
                    "floorspace_detail_gia_gained"
                ][i],
                floorspace_detail_gia_lost=df_tenure_data["floorspace_detail_gia_lost"][
                    i
                ],
                floorspace_detail_superseded_by_lpa_app_no=df_tenure_data[
                    "floorspace_detail_superseded_by_lpa_app_no"
                ][i],
                floorspace_detail_superseded_date=df_tenure_data[
                    "floorspace_detail_superseded_date"
                ][i],
                floorspace_detail_use_class=df_tenure_data[
                    "floorspace_detail_use_class"
                ][i],
                Site_area=df_tenure_data["Site_area"][i],
                parking_net_bluebadge=df_tenure_data["parking_net_bluebadge"][i],
                parking_net_bus=df_tenure_data["parking_net_bus"][i],
                parking_net_carclub=df_tenure_data["parking_net_carclub"][i],
                parking_net_cycle=df_tenure_data["parking_net_cycle"][i],
                parking_net_lgv=df_tenure_data["parking_net_lgv"][i],
                parking_net_car=df_tenure_data["parking_net_car"][i],
                parking_net_motorcycle=df_tenure_data["parking_net_motorcycle"][i],
                parking_net_other=df_tenure_data["parking_net_other"][i],
                parking_net_resi_offstreet=df_tenure_data["parking_net_resi_offstreet"][
                    i
                ],
                parking_no_existing_bluebadge=df_tenure_data[
                    "parking_no_existing_bluebadge"
                ][i],
                parking_no_existing_bus=df_tenure_data["parking_no_existing_bus"][i],
                parking_no_existing_car=df_tenure_data["parking_no_existing_car"][i],
                parking_no_existing_carclub=df_tenure_data[
                    "parking_no_existing_carclub"
                ][i],
                parking_no_existing_cycle=df_tenure_data["parking_no_existing_cycle"][
                    i
                ],
                parking_no_existing_lgv=df_tenure_data["parking_no_existing_lgv"][i],
                parking_no_existing_motorcycle=df_tenure_data[
                    "parking_no_existing_motorcycle"
                ][i],
                parking_no_existing_other=df_tenure_data["parking_no_existing_other"][
                    i
                ],
                parking_no_existing_resi_offstreet=df_tenure_data[
                    "parking_no_existing_resi_offstreet"
                ][i],
                parking_no_proposed_bluebadge=df_tenure_data[
                    "parking_no_proposed_bluebadge"
                ][i],
                parking_no_proposed_bus=df_tenure_data["parking_no_proposed_bus"][i],
                parking_no_proposed_car=df_tenure_data["parking_no_proposed_car"][i],
                parking_no_proposed_carclub=df_tenure_data[
                    "parking_no_proposed_carclub"
                ][i],
                parking_no_proposed_cycle=df_tenure_data["parking_no_proposed_cycle"][
                    i
                ],
                parking_no_proposed_lgv=df_tenure_data["parking_no_proposed_lgv"][i],
                parking_no_proposed_motorcycle=df_tenure_data[
                    "parking_no_proposed_motorcycle"
                ][i],
                parking_no_proposed_other=df_tenure_data["parking_no_proposed_other"][
                    i
                ],
                parking_no_proposed_resi_offstreet=df_tenure_data[
                    "parking_no_proposed_resi_offstreet"
                ][i],
            )
            b.save()
